#!/usr/bin/env python
"""Generate the anonymized TMLR submission from ../paper.tex.

Keeps the author-named preprint (../paper.tex, used for Zenodo) untouched; emits
policy_guided_rag.tex here using the official tmlr.sty (default = double-blind submission,
which auto-anonymizes the author block). Also anonymizes the repo URL in the body.

Run: python build_tmlr.py   (from paper/tmlr/), then: tectonic policy_guided_rag.tex
"""
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE.parent / "paper.tex"
OUT = HERE / "policy_guided_rag.tex"

PREAMBLE = r"""% Auto-generated by build_tmlr.py from ../paper.tex — do not edit by hand.
% Anonymized TMLR submission. The official tmlr.sty (default option) renders the author
% block as "Anonymous authors / Paper under double-blind review".
\documentclass{article}
\usepackage{tmlr}                 % default = submission (double-blind, anonymized)
\usepackage{booktabs}
\usepackage{amsmath,amssymb}
\usepackage{graphicx}
\usepackage{xcolor}
\usepackage{enumitem}
\usepackage{url}
\usepackage[hidelinks]{hyperref}
\graphicspath{{../figures/}}
\newcommand{\guidance}{\textsc{guidance}}
\newcommand{\context}{\textsc{context}}
\newcommand{\cmark}{\textcolor{green!55!black}{$\checkmark$}}
\newcommand{\xmark}{\textcolor{red!70!black}{$\times$}}

\title{Policy-Guided RAG: Asymmetric Visibility for Controllable Retrieval}
\author{\name Anonymous Authors \email anon@example.org}
"""

ANON_REPO = "https://anonymous.4open.science/r/policy-guided-rag"
NAMED_REPO = "https://github.com/Jainil-Gosalia/policy-guided-rag"


def main():
    src = SRC.read_text(encoding="utf-8")
    body = src[src.index(r"\begin{document}"):]   # \begin{document} ... \end{document}

    # Anonymize repo references and point bib at the parent .bib with the TMLR style.
    body = body.replace(NAMED_REPO, ANON_REPO)
    body = body.replace(r"\bibliographystyle{plainnat}", r"\bibliographystyle{tmlr}")
    body = body.replace(r"\bibliography{references}", r"\bibliography{../references}")

    OUT.write_text(PREAMBLE + "\n" + body, encoding="utf-8")
    print(f"Wrote {OUT.name} ({len(PREAMBLE)+len(body)} bytes). "
          f"Compile with: tectonic {OUT.name}")
    # sanity: no author-identifying repo left
    assert NAMED_REPO not in OUT.read_text(encoding="utf-8"), "named repo leaked into anon build"


if __name__ == "__main__":
    main()
